//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int OrderItemsID { get; set; }
        public Nullable<int> OrdersID { get; set; }
        public Nullable<int> TovarsID { get; set; }
        public Nullable<int> CountTovar { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Tovars Tovars { get; set; }
    }
}
