//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int OrdersID { get; set; }
        public Nullable<System.DateTime> DateOrders { get; set; }
        public Nullable<System.DateTime> DateDelivery { get; set; }
        public Nullable<int> PointVudachiesID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> OrderStatusesID { get; set; }
    
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual Users Users { get; set; }
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual PointVudachies PointVudachies { get; set; }
    }
}
