//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointVudachies
    {
        public PointVudachies()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int PointVudachiesID { get; set; }
        public string PointVudachiesName { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
