//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;

namespace StoreShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovars
    {
        public Tovars()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int TovarsID { get; set; }
        public string Article { get; set; }
        public int TovarNamesID { get; set; }
        public string EdIzmereniya { get; set; }
        public int Price { get; set; }
        public int PostavshikesID { get; set; }
        public int ManufacturesID { get; set; }
        public int CategoriesID { get; set; }
        public int Skidka { get; set; }
        public Nullable<int> Ostatok { get; set; }
        public string Opisanie { get; set; }
        public string Images { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufactures Manufactures { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual Postavshikes Postavshikes { get; set; }
        public virtual TovarNames TovarNames { get; set; }

        public string PhotoPath
        {
            get
            {
                if (string.IsNullOrEmpty(Images))
                {
                    return $"/Images/picture.png";
                }
                return $"/Images/{Images}";
            }
        }
        public string Fon
        {
            get
            {
                if (Skidka > 15)
                {
                    return "#2E8B57";
                }
                if (Ostatok == 0)
                {
                    return "#E0F2FE";
                }
                return "#fffff";
            }
        }
        public decimal TotalPrice
        {
            get
            {
                if (Skidka > 0)
                {
                    return Price - (Price * Skidka / 100);
                }
                return Price;
            }
        }
        public Visibility OldPrice
        {
            get
            {
                if (Skidka > 0)
                {
                    return Visibility.Visible;
                }
                return Visibility.Collapsed;
            }
        }
    }
}
