//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TovarNames
    {
        public TovarNames()
        {
            this.Tovars = new HashSet<Tovars>();
        }
    
        public int TovarNamesID { get; set; }
        public string TovarName { get; set; }
    
        public virtual ICollection<Tovars> Tovars { get; set; }
    }
}
